name: CI/CD - Deploy OrbitGuard to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Smoke test (import do app)
        run: |
          source venv/bin/activate
          python -c "import app; print('App importado com sucesso')"

      - name: Deploy para Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: orbitguard-rm550453
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
